version: '3.7'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svt
    ports:
        - "5000:5000"
    restart: always
    environment:
      # APP_DEBUG: "False"
      # APP_HOST: "127.0.0.1"
      # APP_PORT: 5000
      MONGODB_HOSTNAME: mongodb
    user: flaskpy
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    restart: always
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: stacks
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local